module Widgets

import Base: insert!
using Dates
using Unicode
using ..Core
using ..Core: DefaultColorKind, Text
using ..RichContent: default_syntax_registry, render_markdown
using ..Events
using ..Layout
import ..Core: inner, measure, render!

"""Open interaction interface for stateful widgets."""
function handle! end

include("widgets/structure.jl")
include("widgets/text.jl")
include("widgets/containers.jl")
include("widgets/scrolling.jl")
include("widgets/selection.jl")
include("widgets/editing.jl")
include("widgets/input.jl")
include("widgets/visualization.jl")
include("widgets/application.jl")

export ASCII_BORDERS,
       DOUBLE_BORDERS,
       ROUNDED_BORDERS,
       AllBorders,
       Block,
       BorderSet,
       BorderSymbols,
       BottomBorder,
       Bar,
       BarChart,
       Button,
       ButtonState,
       ChoiceOption,
       Box,
       Center,
       CharacterWrap,
       Checkbox,
       CheckboxState,
       Chart,
       ChartDataset,
       Clear,
       Column,
       Grid,
       Gauge,
       Heatmap,
       Histogram,
       EditingBuffer,
       List,
       ListItem,
       ListState,
       MultiSelect,
       MultiSelectState,
       Menu,
       MenuItem,
       MenuState,
       HorizontalRule,
       HorizontalScrollbar,
       Label,
       Heading,
       MarkupText,
       LineGauge,
       LeftBorder,
       NoBorders,
       NoWrap,
       Overlay,
       Padding,
       Paragraph,
       PasswordInput,
       SearchInput,
       SearchInputState,
        NumberInput,
        NumberInputState,
        Tab,
       Tabs,
       TabsState,
       Table,
       TableColumn,
       TableRow,
       TableState,
       TextArea,
       TextAreaState,
       TextInput,
       TextInputState,
       Tree,
       TreeNode,
       TreeState,
       RightBorder,
       RadioGroup,
       RadioGroupState,
       Row,
       Rule,
       RuleDirection,
       Canvas,
       CanvasContext,
       Calendar,
       ScrollState,
       ScrollView,
       Scrollbar,
       ScrollbarDirection,
       Select,
       SelectState,
       Spacer,
       Sparkline,
       Spinner,
       SpinnerState,
       Stack,
       TopBorder,
       Toggle,
       ToggleState,
       VerticalRule,
       VerticalScrollbar,
       WordWrap,
       WrapMode,
       activate,
       backspace!,
       clear_selection!,
       delete_forward!,
       editing_text,
       handle!,
       inner,
       insert!,
       move_cursor!,
       canvas_line!,
       canvas_point!,
       redo!,
       select_all!,
       selected_item,
       selected_value,
       selected_values,
       set_text!,
       undo!,
       Alert,
       Badge,
       CommandItem,
       CommandPalette,
       CommandPaletteState,
       Footer,
       Header,
       HelpView,
       KeyHint,
       LogEntry,
       LogState,
       LogView,
       Notification,
       NotificationCenter,
       NotificationView,
       clear_log!,
       close_palette!,
       dismiss_notification!,
       expire_notifications!,
       open_palette!,
       push_log!,
       push_notification!

end
